### PR TITLE
fix(bypass): use default TTL if bypass response

### LINKED ISSUE #622: `mode: bypass` doesn't work if `Cache-Control: max-age=0`
Hi @darkweak, thanks for building this amazing Caddy module! I love it.

I'm dealing with funky upstreams that do not set their caching headers correctly so I have to use the `mode: bypass`.

I noticed I have to manually drop `Cache-Control` header from upstream responses even with `mode: bypass` for the cache to work.

Similar issue that was fixed before: https://github.com/darkweak/souin/issues/565

### Minimal reproducible example

`Dockerfile.dev`
```Dockerfile
FROM caddy:2.10.0-builder AS builder

RUN xcaddy build \
    --with github.com/darkweak/souin/plugins/caddy \
    --with github.com/darkweak/storages/go-redis/caddy

FROM caddy:2.10.0

# Install bash and curl
RUN apk update && apk add bash curl

# Install Redis
RUN apk update && apk add redis

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

# Copy the Caddy configuration file to the container
COPY config/caddy-dev.json /etc/caddy/caddy-dev.json

# Copy the start script and make it executable
COPY /bin/start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

ENTRYPOINT ["/usr/local/bin/start.sh"]
```

**Build the image**
```
docker build -f Dockerfile.dev -t tls_reverse_proxy_dev .
```

**Run the container**
```
docker run -d --name tls_reverse_proxy_dev \
  -p 80:80 -p 443:443 -p 8082:8082 \
  -v ~/code/tls-reverse-proxy/tls_reverse_proxy_dev/data:/root/caddy-dev/data \
  -v ~/code/tls-reverse-proxy/tls_reverse_proxy_dev/log:/var/log/caddy-dev \
  -v ~/code/tls-reverse-proxy/tls_reverse_proxy_dev/config/caddy-dev.json:/etc/caddy/caddy-dev.json \
  tls_reverse_proxy_dev
```

`caddy-dev.json` (in this container I just simulate the upstream by returning a static response with `Cache-Control: max-age=0` header set.
```
{
  "apps": {
    "cache": {
      "api": {
        "basepath": "/souin-api",
        "souin": {
          "basepath": "/souin",
          "enable": true,
          "security": false
        }
      },
      "log_level": "debug",
      "ttl": "5m",
      "timeout":{
        "backend": "10s",
        "cache": "500ms"
      },
      "redis": {
        "found": true,
        "url": "127.0.0.1:6379"
      }
    },
    "http": {
      "servers": {
        "tls_terminator": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "localhost"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "cache",
                  "Configuration": {
                    "DefaultCache": {
                      "ttl": "300s",
                      "mode": "bypass",
                      "key": {
                        "hide": false,
                        "headers": [
                          "Content-Type",
                          "Authorization"
                        ]
                      }
                    }
                  }
                },
                {
                  "handler": "headers",
                  "response": {
                    "set": {
                      "Cache-Control": ["max-age=0"]
                    }
                  }
                },
                {
                  "handler": "static_response",
                  "body": "Hello, world!",
                  "status_code": 200
                }
              ]
            }
          ],
          "logs": {}
        }
      }
    }
  },
  "admin": {
    "identity": {
      "issuers": [
        {
          "module": "acme",
          "email": "drago@gmail.com"
        }
      ]
    }
  },
  "storage": {
    "module": "file_system",
    "root": "~/caddy-dev/data"
  }
}
```

**Send a request a few times and grep `Cache-Status` header** (notice how it's always stored but next request is a cache miss):
```bash
➜ curl -k -s -X GET https://localhost/test-cache-control -I | grep -i cache-status
cache-status: Souin; fwd=uri-miss; stored; key=GET-https-localhost-/test-cache-control--

➜ curl -k -s -X GET https://localhost/test-cache-control -I | grep -i cache-status
cache-status: Souin; fwd=uri-miss; stored; key=GET-https-localhost-/test-cache-control--
```

**Confirm the response is really stored in Redis**
```bash
➜ curl -k -s -X GET https://localhost/souin-api/souin | jq
[
  "IDX_GET-https-localhost-/test-cache-control--",
  "SURROGATE_",
  "GET-https-localhost-/test-cache-control--"
]
```

That's it! Please let me know if I can provide any more details. I'd love to help!

Thanks!

### PR DESCRIPTION
**Pull request by darkweak**
Closes https://github.com/darkweak/souin/issues/622

cc @popcorn

```
xcaddy build --with github.com/darkweak/souin/plugins/caddy@b3e9362ca1b79602bcc9002b29d1fd6afe81b4ff --with github.com/darkweak/souin@b3e9362ca1b79602bcc9002b29d1fd6afe81b4ff
```

### CODE REVIEW

File: pkg/middleware/middleware.go [hunk 1]
```diff
@@ -284,28 +284,30 @@ func (s *SouinBaseHandler) Store(
...
-	if responseCc.SMaxAge >= 0 {
-		ma = time.Duration(responseCc.SMaxAge) * time.Second
-	} else if responseCc.MaxAge >= 0 {
-		ma = time.Duration(responseCc.MaxAge) * time.Second
-	} else if !modeContext.Bypass_response && customWriter.Header().Get("Expires") != "" {
-		exp, err := time.Parse(time.RFC1123, customWriter.Header().Get("Expires"))
-		if err != nil {
-			return nil
-		}
+	if !modeContext.Bypass_response {
```
Comment (popcorn) [inline pkg/middleware/middleware.go:287]: Should we also check if it's just regular bypass, i.e. `modeContext.Bypass`? If I understand correctly, bypass mode bypasses both request and response headers so maybe we should check it here too?

Comment (popcorn) [reply pkg/middleware/middleware.go:287]: But I'm assuming now that `modeContext.Bypass_response` is `true` if modes are either `bypass_response` or just `bypass`.

Comment (darkweak) [reply pkg/middleware/middleware.go:287]: In the file https://github.com/darkweak/souin/blob/master/context/mode.go we're setting 3 variables:
* Bypass_request if the mode is either `bypass` or `bypass_request`
* Bypass_response if the mode is either `bypass` or `bypass_response`
* Strict if the mode is one of `bypass`, `bypass_request`, `bypass_response`
