### PR TITLE
fix(multiple): december 2024 wave

### LINKED ISSUE #583: Purge with surrogate key not working
Greetings, purging with surrogate keys is not currently working for me.  It looks like the key values are getting stored URL encoded and then being sent to the `Storer` as-is and then not finding the keys to clear:

```
curl -v -H "Authorization: Basic xxx" https://pgs.test/souin-api/souin/surrogate_keys
{"erock-test":",GET-https-erock-test.pgs.test-%2F"}

curl -v -XPURGE -H "Authorization: Basic xxx" -H "surrogate-key: erock-test" https://pgs.test/souin-api/souin/
Status: 204

curl -v -H "Authorization: Basic xxx" https://pgs.test/souin-api/souin/
["GET-https-erock-test.pgs.test-/"]

curl -v -H "Authorization: Basic xxx" https://pgs.test/souin-api/souin/surrogate_keys
{"erock-test":",GET-https-erock-test.pgs.test-%2F"}
```

https://github.com/darkweak/souin/blob/master/pkg/surrogate/providers/common.go#L223

It looks like we might need to expand the QueryUnescape logic? https://github.com/darkweak/souin/blob/master/pkg/surrogate/providers/common.go#L85

### LINKED ISSUE #584: unexpected status code when backend timeout occurs
I am using souin cache as caddy module.

More details are [here](https://caddy.community/t/undocumented-unexpected-timeouts-status-codes-on-souin-cache/26708).

I am getting status code 200 with the body "Internal server error" when the backend does not respond before the `timeout.backend`.

I would expect at least a 504.

### LINKED ISSUE #585: unexpected api endpoint availability
I am using souin as caddy module.

I only cache some of the requests. I was very surprised to notice (after a couple of hours of unsuccessful tries) that in certain configurations the souin api endpoint is not available. More precise, if a request to `/souin-api/souin` is not configured to be cached, the api won't respond.

Like in this `Caddyfile` example:

```
{
    cache
}

:80 {

    @somecache path /i-cache-this
    @nocache not path /i-cache-this

    route @somecache {
        cache
        respond "caching."
    }

    route @nocache {
        respond "not caching. and no souin api."    
    }
}
```

Now, I don't have a sane suggestion. My first instinct would tell me that it would be nice to have the souin-api endpoint liked to the caddy admin port instead. But there are a number of problems with that. 

Perhaps the best solution would br to just document that (with a nice example of how to also secure the souin api endpoint from external).

Keep up the good work, @darkweak !

### LINKED ISSUE #588: Revalidation with If-Modified-Since not working (always returning 200)
Hello! We managed to get Souin integrated into pgs.sh and it's working great so far! https://blog.pico.sh/ann-026-pages-http-caching

I wanted to try out conditional requests (ref: https://github.com/picosh/pico/issues/177) and I noticed that Souin seems to work fine with `If-None-Match: "<etag>"` conditional requests, but doesn't seem to work with `If-Modified-Since: <date>` conditional requests.

Example:

```
# Store the file in the cache

$ curl -iH "Host: picouser-test.pgs.dev.pico.sh" localhost:3000/file.txt                                                       
HTTP/1.1 200 OK
Cache-Control: max-age=600
Cache-Status: Souin; fwd=uri-miss; stored; key=GET-http-picouser-test.pgs.dev.pico.sh-/file.txt
Content-Length: 14
Content-Type: text/plain
Etag: "a9a83095955b3d3efacc7f833a103cb2-1"
Last-Modified: Sat, 21 Dec 2024 03:03:10 GMT
Surrogate-Key: picouser-test
Date: Sat, 21 Dec 2024 15:24:23 GMT

Hello, World!

# Send conditional request
$ curl -iH "Host: picouser-test.pgs.dev.pico.sh" -H "If-Modified-Since: Sat, 21 Dec 2024 09:09:10 GMT"  localhost:3000/file.txt
HTTP/1.1 200 OK
Age: 56
Cache-Control: max-age=600
Cache-Status: Souin; hit; ttl=544; key=GET-http-picouser-test.pgs.dev.pico.sh-/file.txt; detail=OTTER
Content-Length: 14
Content-Type: text/plain
Date: Sat, 21 Dec 2024 15:24:23 GMT
Etag: "a9a83095955b3d3efacc7f833a103cb2-1"
Last-Modified: Sat, 21 Dec 2024 03:03:10 GMT
Surrogate-Key: picouser-test

Hello, World!
```

It should have returned a 304 Not Modified response. Any ideas?

### PR DESCRIPTION
**Pull request by darkweak**
Closes #584 
Closes #583 
Closes #588 
Closes #585 

Cache-handler:
Closes https://github.com/caddyserver/cache-handler/issues/116
Closes https://github.com/caddyserver/cache-handler/issues/118

Storages:
Closes https://github.com/darkweak/storages/issues/23

### CODE REVIEW

File: context/now.go [hunk 1]
```diff
@@ -19,8 +19,16 @@ func (*nowContext) SetContextWithBaseRequest(req *http.Request, _ *http.Request)
...
 func (cc *nowContext) SetContext(req *http.Request) *http.Request {
-	now := time.Now().UTC()
-	req.Header.Set("Date", now.Format(time.RFC1123))
+	var now time.Time
+	var e error
+
+	now, e = time.Parse(time.RFC1123, req.Header.Get("Date"))
+
+	if e != nil {
+		now := time.Now()
```
Comment (imlonghao) [inline context/now.go:28]: Is it on purpose to use :=?
In this case, it will remain unset when return.

https://go.dev/play/p/-br5etSvh20

Comment (darkweak) [reply context/now.go]: @imlonghao updated in the last commit, thank you for this comment. 👍
